- name: Download Remi Repository RPM
  get_url:
    url: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    dest: /tmp/remi-release-8.rpm

- name: Install Remi Repository RPM
  dnf:
    name: /tmp/remi-release-8.rpm
    state: present

- name: Enable Redis Module
  dnf:
    name: redis:remi-6.2
    state: enabled
    update_cache: yes

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: update the lisiting address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf

- name: enable and restarting redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true
