- name: Install redis
  ansible.builtin.shell: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y ; dnf module enable redis:remi-6.2 -y ; dnf install redis -y 

- name: update the lisiting address
  ansible.builtin.replace:
    path: 
      - /etc/redis.conf
      - /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: enable and restarting redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true