- name: Install redis
  ansible.builtin.dnf: 
    name: "{{item}}"
    state: latest
    disable_gpg_check: true
  loop:
   - https://rpms.remirepo.net/enterprise/remi-release-8.rpm
   - redis 

- name: update the lisiting address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: enable and restarting redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true