- name: Getting the repo and enableing 6.2
  ansible.builtin.shell: "{{item}}"
  loop:
    - dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
    - dnf module enable redis:remi-6.2 -y
  disable_gpg_check: true

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: update the lisiting address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf

- name: enable and restarting redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: true
