- name: Create or update key/value pair in AWS SSM parameter store
  hosts: all
  become: yes
  tasks:
    community.aws.ssm_parameter:
      name: "Hello"
      description: "This is your first key"
      value: "World"