- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: remove the default nginx content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create HTTP Document Directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: get the front end code from repo to the default location
  ansible.builtin.git:
    repo: https://github.com/roboshop-Project/frontend.git
    dest: /usr/share/nginx/html

- name: Copy the nginx conf file
  ansible.builtin.template:
     src: roboshop.conf
     dest: /etc/nginx/default.d/roboshop.conf


- name: Enabling and restarting nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes