- name: Mongodb repo file
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: installing mongo client
  ansible.builtin.dnf:
    name: mongodb-org-shell
    state: present

- name: loading the mongo schema
  ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.mongodb', region='us-east-1') }} </app/schema/user.js
