- name: python for mysql
  ansible.builtin.dnf:
    name: "{{item}}"  
    state: present
  loop:
    - python3.11-devel
    - python3.11-pip
    
- name: installing sql client
  ansible.builtin.dnf:
    name: mysql
    state: present

  
- name: Load MySQL Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/{{component}}.sql
    login_host: "{{ lookup('aws_ssm', 'dev.mysql', region='us-east-1') }}"
    login_user: root
    login_password: "{{ lookup('aws_ssm', 'dev.mysql.pass', region='us-east-1') }}"
